---
# Dynamic variables here will be compiled to individual files in compiled/attributes.
attributes:
  environment: production
  ruby_version: 2.1.2
  postgres_version: 9.3 #to find config file to update, please make sure this matches your postgres version
  postgres_user: 
  postgres_database: 
  postgres_password: 
  deploy_user: 
  app_name: 

# Remote recipes here will be downloaded to compiled/recipes.
recipes:
  # rvm: https://raw.github.com/kenn/sunzi-recipes/master/ruby/rvm.sh
  # dotdeb: https://raw.github.com/kenn/sunzi-recipes/master/debian/dotdeb-wheezy.sh
  # backports: https://raw.github.com/kenn/sunzi-recipes/master/debian/backports-wheezy.sh
  # mongodb-10gen: https://raw.github.com/kenn/sunzi-recipes/master/debian/mongodb-10gen.sh

# Files specified here will be copied to compiled/files.
# files:
#   - ~/.ssh/id_rsa.pub

# Fine tune how Sunzi should work.
preferences:
  # Erase the generated folder on the server after deploy.
  # Turn on when you are done with testing and ready for production use.
  erase_remote_folder: true

  # Skip retrieving remote recipes when local copies already exist. This setting helps
  # iterative deploy testing considerably faster, when you have a lot of remote recipes.
  cache_remote_recipes: true

  # Evaluate files as ERB templates. When enabled, you can pass dynamic values in the form
  # of <%= @attributes.environment %> in recipes, roles, files and install.sh.
  eval_erb: true
